sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-041
env:
  global:
    -
      # LTD_AWS_ID
      secure: GVsYwoIBRVRr9ggFcvkhywqKVUjWclugWg8xD/Sv/0YnaqGmRMffHi5DVYgsx2fpR76KN5z5UKNM5wZLwbTC7DHCtCXuPi/IfI0ShT+uoHNzelPxoTxzxddBh/EJf6x2DOcIXu93I94yYDIBblFZsXgrPBA/pEYbJLeii9qEDPYvbaN0ge9p/AZcljsQxQXNg3uNEHGxyEFxNR20ozVC1T8ciAmZ2Luuv6c3NJ6mjkrxGg4EG9ht7O1UYr/acTin02I5/s90MF3P2mL8avuJUC1Ot94sIiz0gf5bVNHcOzNI27NQfXZpx6aeXVeHDrT/o+CeEJwODFe15w20yyJLkP8p87tNKIZh+zF21vYkJPaJoyB7ntzbhP/RisrGzBHr4LaJunycSBS4EDQabbj1XANgr6NXrnkN+MFn/SH05H0pOTTD717Xr8O6prRJLudC01lWbFTPGhYvc7bVTsyf3uzVgjJF9gl3hz/KcKrMcZZEKT/FowCijfy8/w0YS90r1d+7/0jpIst8Mu6dFI0TTWigVbimP75AS+M5vKHQHULTjRcquzQgKozD1AgJQePoVsZb+9j988YFKahDAFGBVLHXFazH91aQ7qvptOkMlYgoTv06cx/z9vkEoui0hfodDBMR70gQJ7jJVdkZVsCF+9isehq/jFEH0wnvwECexU8=
    -
      # LTD_AWS_SECRET
      secure: hsXvGIb0gYdYOazxmnIgtF5jq16gC3mxs6Tx33glf/WVhULymZeBtBvm57UIiTbqtFzZdTtKEX+8Av4z3q2KQ0CHHRy3qg2KAS5fbI1svpUFDED11diOnqKYOiaPON8RNMCRZRCRVhsi9+29zq9QwJXLJoDm3VVV2SkKLWUJVQI6Qfkqh364dL3TPYWq9gOawOl9ZYTbqs5bl5E/UnVC+D2C89KUdJgcZZ+mA03cdMKwQRVkL6a21atAdYttyxrADtrQCg/bi9PajguomuHMONgIGUU10yqzdxCzZtptXup+Xsw4GgdTg26+3laUsbM2MVt7/XRMzOvXq9pmaJdX/uKxPZs2E+FCQVDz3m9haLnZID3Z/eHIMXdnK824q+fwE7AZ2vmsLjPwQCV9epQOnPI4E40gJZR5v26MjUBTEiNVynqFrWiyfdsw2GW1vNBKbmn7kdlgsc0tDhhV1sI0/KpW1Skd9Ml66oHWs8QHeQLgWVBAdKFdXvsx4TGnhF1f5VyqAth5vFSE3kDDkcW6t3nCC7vwObYHCg88EkIAyPDSCAZf+MkCR06XW1GlyD5t9uCpADb9ElDAAFz9WrxE8raZhZeLSoyWHxc7k/r8TFE90xknOaRYKNHnEx5fmCo/zjy0UVIDKI038rWtpxRj1zH/LsnQ/I3e2yPjHxT1G8w=
    -
      # LTD_USERNAME
      secure: uP6QqXPZLbdfsZ0knmJR9jQqXF3Zjh2qO8U+YO5lT2zncHznMboL0onX0mGn6fmZIuiQeBPBHPSeQAhF9V5Uc7JaK5IHlZyFxAiYioksOzaxGvDbI8MOj8C+rcz3qafVF7/XQEEelO/cAa7pA/oQQBOHnHO6FBQH3buTJOCAFbuqJ6Unvs9k/bMCTUGmglmbXsZDHToJkKjGXDe6NDDutUj79urpKofxrBy7A7xb8IjffK2SVljuSdGb9VRaUNZJ6FoE11ZoaVr/Dfb+0Xp8TX/cliObJkQE4xAps/Ux4e3dhOq156ZDI3slHoKSrtCyF/dXda7JRfG9Xr4R8eg0t8M9EGUmAl9ums5scalnFsqhzNUYnu26ekuX1AI+mq7h+DRUqgD3CDrvPtK7iUhr+EtcZke3jYCJFTwsXYJ7DnhzFygh9AIwgT1rQa6F2DmxZXycDxEszDUT/c3F9WTzQIJiX+LeE6jMIRLDW72BFKu8Fe2+EcULC8Dts2KBaUhtKs4e7JtnKs1Qo5rhTun+0lMWOuArfNs2+FfjNjxCJ9xQYjJy0PfTm4sHXQCG9wX5IrlsGyo8hYVTskqJj0EhNOBBL3rNpQ0KNCwz9x3jJPwwzu3aL1CiEQGxGUDD1Yv+phqtnan8f81ggtppn3Hq62HhPKDkmU5sUtuwtYgFv2E=
    -
      # LTD_PASSWORD
      secure: C4dbVW0ICCM0csGoqPg+0x2LokE+bL/NEj3VMQgvM+pJx3X6OyVJR2C7kCNXmiUiKQqapIs9nQptsMJmpCNRiIgJyEt2h8YrYurPyYMWRXvluWK2T1TR6lQ/KayIzeb81uIZhrlKmDl7Vr3Jq77ugW+BKS29VmM0JF66PUPVkJLUD35/R5ZfXi2i5SNKojk+6rTDiuazVLcyVAJdeYMvYqNsRPjuJRC8d2BFWWfJB4E6tP9Ym6VIYwXMPEDhp9qn2SE2/qUxx8eBbu1Rboky3bEQFOn7eGWoO1bA7gMjHvIWLlYj3T7VozKuwwrYR9g6qlPC79tAzq1hHgLq4Pvx2YZxhYHamI0FFJy3fHUevaAtFbeevnbufEYAhdxWSSXlSzcXKTs2u8JcS2mbknHIB4gkFplkcnr5n0HXVpR7B5/EahaP/394ZEUxWqyEyT5NjMzCf17jxe88WlK9TdBQuOPubUSIzyqYc68PykqyJI28sQXlMvn25WHquTT24Nj9n8ntIvui3TgV1ad/9zI+PObG0gMV5h8ft6YaP0zChA0pDCbPXRvumbejiIznEqYEWQ/j5djIjFHc93SEZyiPzLz/0z2ppmsjWrqiztCCQ0IEN0O1td4jpbmx631drNAsG1h9iBusAgSRoD1os0loCdcSwbGGh6Adjco5o4i/Iro=
